services:
  tasks_app:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: tasks_backend_app
    ports:
      - "9090:80"
    volumes:
      - ./backend:/var/www/html:delegated
    depends_on:
      - mysql
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0&charset=utf8mb4"

  mysql:
    image: mysql:8.0
    container_name: tasks_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tasks_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql

  tasks_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        INTERNAL_BACKEND_URL: ${INTERNAL_BACKEND_URL}
        NEXT_PUBLIC_TIMEOUT_TOAST: ${NEXT_PUBLIC_TIMEOUT_TOAST}
        NEXT_PUBLIC_TIMEOUT_REDIRECT: ${NEXT_PUBLIC_TIMEOUT_REDIRECT}
    container_name: tasks_frontend_app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
      - /app/.next
    depends_on:
      - tasks_app
    environment:
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      INTERNAL_BACKEND_URL: ${INTERNAL_BACKEND_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXT_PUBLIC_TIMEOUT_TOAST: ${NEXT_PUBLIC_TIMEOUT_TOAST}
      NEXT_PUBLIC_TIMEOUT_REDIRECT: ${NEXT_PUBLIC_TIMEOUT_REDIRECT}

volumes:
  mysql_data:
